apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: do2pg1gab-python-gitops
  description: This is GitOps manifest for do2pg1gab-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: do2pg1gab-python
    backstage.io/kubernetes-id: do2pg1gab-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: do2pg1gab-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:do2pg1gab-python
