apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: do2pg1gab-python
  janus-idp.io/tekton: do2pg1gab-python
  backstage.io/kubernetes-id: do2pg1gab-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: do2pg1gab-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
