apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: do2pg1gab-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: do2pg1gab-python 
  name: do2pg1gab-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: do2pg1gab-python 
